[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "Training crate for the Burn framework"
edition = "2021"
keywords = ["deep-learning", "machine-learning", "tensor", "pytorch", "ndarray"]
license = "MIT OR Apache-2.0"
name = "burn-train"
readme = "README.md"
repository = "https://github.com/burn-rs/burn/tree/main/burn-train"
version = "0.9.0"

[dependencies]
burn-core = {path = "../burn-core", version = "0.9.0" }

# Console
indicatif = "0.17.5"
log = {workspace = true}
log4rs = {workspace = true}

# Metrics
nvml-wrapper = "0.9.0"
rgb = "0.8.36"
terminal_size = "0.2.6"
textplots = "0.8.0"

# Utilities
derive-new = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}

[dev-dependencies]
burn-ndarray = {path = "../burn-ndarray", version = "0.9.0" }
