[workspace]
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
  "burn",
  "burn-autodiff",
  "burn-common",
  "burn-core",
  "burn-dataset",
  "burn-derive",
  "burn-import",
  "burn-ndarray",
  "burn-no-std-tests",
  "burn-tch",
  "burn-wgpu",
  "burn-tensor-testgen",
  "burn-tensor",
  "burn-train",
  "examples/*",
]

[workspace.dependencies]
bytemuck = "1.13"
const-random = "0.1.15"
csv = "1.2.2"
dashmap = "5.4.0"
dirs = "5.0.1"
fake = "2.6.1"
flate2 = "1.0.26"
gix-tempfile = {version = "7.0.0", features = ["signals"]}
hashbrown = "0.14.0"
indicatif = "0.17.5"
libm = "0.2.7"
log = "0.4.19"
log4rs = "1.2.0"
pretty_assertions = "1.3"
proc-macro2 = "1.0.60"
protobuf-codegen = "3.2"
quote = "1.0.28"
r2d2 = "0.8.10"
r2d2_sqlite = {version = "0.22.0", features = ["bundled"]}
rayon = "1.7.0"
rmp-serde = "1.1.1"
rstest = "0.18.1"
rusqlite = {version = "0.29", features = ["bundled-full"]}
sanitize-filename = "0.4.0"
serde_rusqlite = "0.33.1"
spin = {version = "0.9.8", features = ["mutex", "spin_mutex"]}
strum = "0.24"
strum_macros = "0.24"
syn = {version = "2.0", features = ["full", "extra-traits"]}
tempfile = "3.6.0"
thiserror = "1.0.40"
topological-sort = "0.2.2"

# WGPU stuff
futures-intrusive = "0.5"
pollster = "0.3"
text_placeholder = {version = "0.5.0", features = ["struct_context"]}
wgpu = "0.17.0"

#
# The following packages disable the "std" feature for no_std compatibility
#
bincode = {version = "2.0.0-rc.3", features = ["alloc", "serde"], default-features = false}
derive-new = {version = "0.5.9", default-features = false}
half = {version = "2.3.1", features = ["alloc", "num-traits", "serde"], default-features = false}
ndarray = {version = "0.15.6", default-features = false}
num-traits = {version = "0.2.15", default-features = false, features = ["libm"]}# libm is for no_std
rand = {version = "0.8.5", default-features = false, features = ["std_rng"]}# std_rng is for no_std 
rand_distr = {version = "0.4.3", default-features = false}
serde = {version = "1.0.164", default-features = false, features = ["derive", "alloc"]}# alloc is for no_std, derive is needed
serde_json = {version = "1.0.96", default-features = false}
uuid = {version = "1.3.4", default-features = false}
