[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "named-tensor"
publish = false
version = "0.9.0"

[dependencies]
burn = {path = "../../burn", features = ["experimental-named-tensor"]}
burn-autodiff = {path = "../../burn-autodiff"}
burn-ndarray = {path = "../../burn-ndarray"}

# Serialization
serde = {workspace = true, features = ["std", "derive"]}
