[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "text-generation"
publish = false
version = "0.9.0"

[features]
default = []
f16 = []

[dependencies]
# Burn
burn = {path = "../../burn"}
burn-autodiff = {path = "../../burn-autodiff"}
burn-tch = {path = "../../burn-tch"}

# Tokenizer
tokenizers = {version = "0.13.3", default-features = false, features = [
  "onig",
  "http",
]}

# Utils
derive-new = {workspace = true}
log = {workspace = true}
serde = {workspace = true, features = ["std", "derive"]}
