[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "onnx-inference"
publish = false
version = "0.9.0"

[features]
default = []

[dependencies]
burn = {path = "../../burn"}
burn-dataset = {path = "../../burn-dataset"}
burn-ndarray = {path = "../../burn-ndarray"}
serde = {workspace = true}

[build-dependencies]
burn-import = {path = "../../burn-import"}
