name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-burn-derive:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-derive
    secrets: inherit

  publish-burn-dataset:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-dataset
    secrets: inherit

  publish-burn-common:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-common
    secrets: inherit

  publish-burn-tensor-testgen:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    with:
      crate: burn-tensor-testgen
    secrets: inherit

  publish-burn-tensor:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor-testgen
    with:
      crate: burn-tensor
    secrets: inherit

  publish-burn-autodiff:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-tensor-testgen
      - publish-burn-common
    with:
      crate: burn-autodiff
    secrets: inherit

  publish-burn-tch:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
    with:
      crate: burn-tch
    secrets: inherit

  publish-burn-ndarray:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-common
    with:
      crate: burn-ndarray
    secrets: inherit

  publish-burn-wgpu:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-ndarray
      - publish-burn-common
    with:
      crate: burn-wgpu
    secrets: inherit

  publish-burn-core:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-tensor
      - publish-burn-autodiff
      - publish-burn-dataset
      - publish-burn-derive
      - publish-burn-ndarray
      - publish-burn-common
    with:
      crate: burn-core
    secrets: inherit

  publish-burn-train:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-core
    with:
      crate: burn-train
    secrets: inherit

  publish-burn:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn-core
      - publish-burn-train
    with:
      crate: burn
    secrets: inherit

  publish-burn-import:
    uses: burn-rs/burn/.github/workflows/publish-template.yml@main
    needs:
      - publish-burn
    with:
      crate: burn-import
    secrets: inherit
